### PR TITLE
login page ui added

### PR DESCRIPTION
**Pull request by ShreyashMahajan**
Login Page UI is added in this PR

### CODE REVIEW

**Review by dev-enforced — APPROVED** [review]
Class naming looks good!! Do link to the signup page UI here

**Review by ozairkhan2810 — APPROVED** [review]
everything looks good, just remove comments

**Comment by ShreyashMahajan** [comment]
> Class naming looks good!! Do link to the signup page UI here

thank you, i will link that

**Comment by ShreyashMahajan** [comment]
> everything looks good, just remove comments

ok thank you

**Pull request merged**
